In [1]:
import numpy as np
import pandas as pd
import pytz
from datetime import datetime, date

instantiate date/time objects

In [6]:
x = pd.to_datetime("2024-05-06")
x.value # timestampe value in ns

# datetime index
dates = pd.date_range('2024-01-01', '2024-12-31', freq="WOM-3FRI")

In [9]:
start_date = date(2012,12,31)
end_date = datetime.now().date()
dates = pd.date_range(start=start_date, end=end_date, freq='B')
# assumes the price mvmt is Guassian
mvmt = np.random.standard_normal(len(dates))

In [10]:
px = 100
px_series = []
for chg in mvmt:
    px = px * mvmt
    px_series.append(px)

<ipython-input-10-f64cb3934835>:4: RuntimeWarning: overflow encountered in multiply
  px = px * mvmt


In [11]:
px_series

[array([-54.0795272 , 109.93265755, -26.26157778, ..., 150.98316857,
        -38.59812869, -11.22505919]),
 array([ 29.24595262, 120.85189196,   6.89670467, ..., 227.95917191,
         14.89815539,   1.26001954]),
 array([-1.58160729e+01,  1.32855697e+02, -1.81118346e+00, ...,
         3.44179981e+02, -5.75040919e+00, -1.41437939e-01]),
 array([8.55325744e+00, 1.46051798e+02, 4.75645354e-01, ...,
        5.19653841e+02, 2.21955034e+00, 1.58764923e-02]),
 array([-4.62556119e+00,  1.60558623e+02, -1.24911975e-01, ...,
         7.84589834e+02, -8.56704896e-01, -1.78214566e-03]),
 array([2.50148162e+00, 1.76506361e+02, 3.28038553e-02, ...,
        1.18459859e+03, 3.30672058e-01, 2.00046905e-04]),
 array([-1.35278943e+00,  1.94038133e+02, -8.61480999e-03, ...,
         1.78854449e+03, -1.27633227e-01, -2.24553835e-05]),
 array([7.31582129e-01, 2.13311277e+02, 2.26238502e-03, ...,
        2.70040114e+03, 4.92640371e-02, 2.52063009e-06]),
 array([-3.95636157e-01,  2.34498755e+02, -5.94138003e

In [7]:
data = pd.DataFrame({"date": dates, "mvmt": mvmt})

385